#!/usr/bin/env python3
"""Build sr:competitor -> relative flag PNG path map for WC2026 HTML.

Reads wc2026_schedule.csv and assets/sportradar-country-flags/index.json,
resolves Sportradar schedule team labels to manifest country names, emits
assets/wc2026_competitor_flags.embed.js for use in wc2026_schedule.html.
"""

from __future__ import annotations

import csv
import json
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
CSV_PATH = REPO_ROOT / "wc2026_schedule.csv"
INDEX_PATH = REPO_ROOT / "assets" / "sportradar-country-flags" / "index.json"
OUT_PATH = REPO_ROOT / "assets" / "wc2026_competitor_flags.embed.js"

# Schedule CSV names -> Sportradar manifest country_name (see index.json)
SCHEDULE_NAME_TO_MANIFEST: dict[str, str] = {
    "USA": "UNITED STATES",
    "Korea Republic": "KOREA REPUBLIC OF",
    "Czechia": "CZECH REPUBLIC",
    "IR Iran": "IRAN ISLAMIC REPUBLIC OF",
    "Turkiye": "TURKEY",
    "Ivory Coast": "COTE D IVOIRE",
    "Congo DR": "CONGO DEMOCRATIC REPUBLIC",
}


def norm_key(s: str) -> str:
    return " ".join(s.upper().split())


def is_placeholder_team_name(name: str) -> bool:
    """Aligned with wc2026_schedule.html isPlaceholderTeam (knockout slots)."""
    n = (name or "").strip()
    if not n:
        return True
    if re.match(r"^[0-9]", n):
        return True
    if re.match(r"^W\d", n, re.I):
        return True
    if re.match(r"^RU\d", n, re.I):
        return True
    if "/" in n and re.search(r"\d", n):
        return True
    return False


def manifest_path_for_team_name(team: str, by_manifest_name: dict[str, str]) -> str | None:
    if team in SCHEDULE_NAME_TO_MANIFEST:
        mn = SCHEDULE_NAME_TO_MANIFEST[team]
    else:
        mn = team.upper().strip()
    return by_manifest_name.get(norm_key(mn))


def main() -> int:
    if not INDEX_PATH.exists():
        print(f"Missing {INDEX_PATH}", file=sys.stderr)
        return 1
    if not CSV_PATH.exists():
        print(f"Missing {CSV_PATH}", file=sys.stderr)
        return 1

    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    by_manifest_name: dict[str, str] = {}
    for row in index:
        if not isinstance(row, dict):
            continue
        cname = (row.get("country_name") or "").strip()
        f = row.get("file") or {}
        rel = (f.get("relative_to_repo") or "").strip()
        if cname and rel:
            by_manifest_name[norm_key(cname)] = rel

    comp_to_path: dict[str, str] = {}
    unmapped: list[tuple[str, str]] = []

    with CSV_PATH.open(newline="", encoding="utf-8") as fp:
        r = csv.DictReader(fp)
        for row in r:
            for col_id, col_name in (
                ("home_team_id", "home_team"),
                ("away_team_id", "away_team"),
            ):
                cid = (row.get(col_id) or "").strip()
                name = (row.get(col_name) or "").strip()
                if not cid or not cid.startswith("sr:competitor:"):
                    continue
                if is_placeholder_team_name(name):
                    continue
                if cid in comp_to_path:
                    continue
                p = manifest_path_for_team_name(name, by_manifest_name)
                if p:
                    comp_to_path[cid] = p
                else:
                    unmapped.append((cid, name))

    if unmapped:
        for cid, name in sorted(set(unmapped), key=lambda x: (x[1], x[0])):
            print(f"warning: no flag for {cid} ({name!r})", file=sys.stderr)

    pairs = ",\n  ".join(
        f"{json.dumps(k)}: {json.dumps(v)}" for k, v in sorted(comp_to_path.items())
    )
    body = f"""// Auto-generated by scripts/gen_wc2026_flag_map.py — do not edit by hand.
const WC2026_FLAG_BY_COMPETITOR_ID = {{
  {pairs}
}};
"""
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(body, encoding="utf-8")
    print(f"Wrote {len(comp_to_path)} competitor flag paths to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
